name: Build and publish documentation
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      output-dir:
        required: true
        type: string
      wiki-repo:
        required: true
        type: string
        description: The repo owner name and repo name
    secrets: 
      WIKI:
        required: true

jobs:
  docfx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Authenticate to GithubPackages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" \
          --name "dmcphgh" \
          --username "${{ github.repository_owner }}" \
          --password "${{secrets.WIKI}}" \
          --store-password-in-clear-text
      - name: Install DocFX
        run: dotnet tool install -g docfx
      - name: Build DocFX
        run: |
          cd ${{inputs.project-name}}
          docfx metadata docfx.json
          docfx build docfx.json
      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true