on:
  pull_request:
    branches:
      - master
    paths:
      - 'Vectra.AST/**'
      - '.github/workflows/*'
    types:
      - closed
        
permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  build:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release.yaml
    with:
      project-name: Vectra.AST
      nuget-output: nupkgs/ast
    secrets: 
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
  doc:
    needs: build
    uses: ./.github/workflows/documentation.yaml
    with:
      project-name: Vectra.AST
      output-dir: docs/wiki
      wiki-repo: ${{github.repository}}
    secrets:
      wiki-token: ${{secrets.WIKI_TOKEN}}
